import type { Metadata } from "next";
import "./globals.css";

// fonts
import { Poppins } from "next/font/google";

// swiper
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import IsLogin from "@/lib/isLogin";
import { Query } from "@/providers/component";

const poppins = Poppins({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Putra Tunggal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <Query>
          <main>
            {children}
            <IsLogin />
          </main>
        </Query>
      </body>
    </html>
  );
}
