name: CI/CD Pipeline for Putra Tunggal

on:
  push:
    branches:
      - main # Jalankan hanya saat ada perubahan di branch "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy the application to the VPS
      - name: Deploy to GCP
        run: |
          sshpass -p "${{ secrets.USER_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.USER_VPS }} << 'EOF'
          
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # Ini memuat nvm

            nvm use 20 # Pastikan menggunakan Node.js versi 20
            node -v    # Verifikasi versi Node.js
            npm -v     # Verifikasi versi npm

            cd putra-tunggal
            git pull origin main
            npm install

            export DATABASE_URL=${{ secrets.DATABASE_URL }} 
            export JWT_SECRET=${{ secrets.JWT_SECRET }} 
            export NEXT_PUBLIC_BASE_URL=${{ secrets.NEXT_PUBLIC_BASE_URL }} 
            export NEXT_PUBLIC_ROLE_USER=${{ secrets.NEXT_PUBLIC_ROLE_USER }} 
            export MIDTRANS_SERVER_KEY=${{ secrets.MIDTRANS_SERVER_KEY }} 
            export MIDTRANS_CLIENT_KEY=${{ secrets.MIDTRANS_CLIENT_KEY }} 

            npm run build
            
            pm2 restart 1 --update-env

            # Save PM2 process list
            pm2 save

          EOF
